info:
    description: "ArrayTest REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "ArrayTest"
    version: v1.0
openapi: 3.0.1
components:
    schemas:
        OutboxEntryResponse:
            type: object
            description: ""
            properties:
                ID:
                    type: integer
            xml:
                name: OutboxEntry
        OutboxEntries:
            description: ""
            type: array
            items:
                $ref: "#/components/schemas/OutboxEntryResponse"
            example:
                - id: 10
                - id: 20
            xml:
                name: OutboxEntries
                wrapped: true
paths:
    "/outbox-entries":
        get:
            operationId: getOutboxEntries
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        ""
            tags: [ "OutboxEntries" ]